### PR TITLE
PCT Build + SonarQube analysis

### PR DESCRIPTION
**Pull request by gquerret**

### CODE REVIEW

**Comment by gquerret** [comment]
Yes, that's required to execute the SQ analysis in an automated way. Otherwise, this has to be done manually with the files in my own clone, and I'd have to merge on a regular basis, which is not something I'd be happy to do :)

And don't merge for now, I just saw that the JAR files are included in the PR, I'll remove them.

**Comment by patrickTingen** [comment]
Hi Gilles, any idea when I can merge this?

**Comment by gquerret** [comment]
I should be able to find some time before the end of the week.

**Comment by gquerret** [comment]
Branch is ready !

**Comment by patrickTingen** [comment]
Merged, thanks for your efforts!

**Pull request merged**
